name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node.js 16.*
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: install clasp
        run: npm install -g @google/clasp
      - name: install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: install prettier
        run: npm install -g prettier
      - name: format README.md
        run: npm run lint
      - name: format code
        run: npm run format
      - name: create > ~/.clasprc.json
        run: |
          cat << EOS > ~/.clasprc.json
          {
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.webapp.deploy openid",
              "token_type": "Bearer",
              "id_token": "${{ secrets.ID_TOKEN }}",
              "expiry_date": 1641493053167,
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}"
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS
      - name: create .clasp.json
        run: |
          cat << EOS > .clasp.json
          {
            "scriptId": "${{ secrets.SCRIPT_ID }}",
            "rootDir": "./src",
            "fileExtension": "ts"
          }
          EOS
      - name: push to clasp
        run: clasp push -f
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()
